server:
  port: 8080

spring:
  application:
    name: falletterbev2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      client-type: lettuce
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.hibernate.sql: debug
